import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Feed from '../components/Feed';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Comazine</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width,initial-scale=1.0,maximum-scale=1.0'
        ></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Feed />
    </div>
  );
};

export default Home;
